[package]
name = "zedico"
version = "0.1.0"
authors = ["Joël J. Présent <36854931+joeljpresent@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
description = "Representation of French words (alpha version)."

[dependencies]
