[package]
name = "zedico"
version = "0.1.1"
authors = ["Joël J. Présent <36854931+joeljpresent@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
description = "Representation of French words (alpha version)."

[dependencies]
